---
# tasks file for deploy-frontend
- name: install httpie
  package:
    name: httpie
    state: latest
 
- name: install HAProxy
  yum:
    name: haproxy
    state: latest

- name: enable HAProxy
  service:
    name: haproxy
    state: started

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart_haproxy
